Fix : error in commad to call backup method in backup script Fix : neverending blocking backup script if it wasn't stopped correctly before Fix : Can't save multimedia on instance and not on another Improve : Help messages on config panel Fix : Cannot seeing backups on default local repo (backup menu on Yunohost admin)

diff --git a/conf/backup b/conf/backup
--- a/conf/backup
+++ b/conf/backup
@@ -6,11 +6,14 @@
 #                     GLOBAL VARS                         #
 #=========================================================#
 
-declare -r CURRENT_DATE=$(date +"%Y%m%d-%H%M%S")
 # log file for mail notification
 declare -r LOG_FILE=$(mktemp)
+# Script name
+declare -r SCRIPT_PATH="$(readlink -f "${BASH_SOURCE}")"
 # Global to store errors messages for mail
 ERRORS=""
+# If we force execution (without checking already script executing)
+FORCE=false
 
 #=========================================================#
 #                    SCRIPT FUNCTIONS                     #
@@ -37,97 +40,166 @@ usage() {
 Script used to launch Yuno-archive backup according to configuration
 
 Usage  :
-   $(basename "$0") APP_ID [Options]
+   $(basename "$0") [Options]
 
-Arguments :
-    APP_ID : Yuno-archive application Id (mandatory)
 
 Options :
    -h : Show this message
+   -f : Force script execution (do not check if there is another instance running)
 MSG_USAGE
+}
+
+### FUNCTION BEGIN
+# Ending script and send mail according to configuration
+# ARGUMENTS:
+#   $1 (integer) exit value.
+# GLOBALS:
+#   ERRORS
+### FUNCTION END
+end_script() {
+    exit_value=${1-0}
+
+    method="$(sudo yunohost app setting "__APP__" method)"
+    repository="$(sudo yunohost app setting "__APP__" "${method}_repository")"
+    mailalert="$(sudo yunohost app setting "__APP__" mailalert)"
+    if [[  -n "$ERRORS" && $mailalert != "never" ]]; then
+        cat <(echo -e "$ERRORS\n\n\n") "$LOG_FILE" | mail -a "Content-Type: text/plain; charset=UTF-8" -s "[Yuno-archive] Backup __APP__ failed onto $method $repository" admins
+    elif [ "$mailalert" == "always" ]; then
+        mail -a "Content-Type: text/plain; charset=UTF-8" -s "[Yuno-archive] Backup __APP__ succeeded onto $repository" admins < "$LOG_FILE"
+    fi
+
+    # restore .nobackup file
+    if [[ -e  /home/yunohost.multimedia/.nobackup_disabled ]]; then
+        mv /home/yunohost.multimedia/.nobackup_disabled /home/yunohost.multimedia/.nobackup
+    fi
+    rm -rf "$LOG_FILE"
+    exit $exit_value
+}
+
+### FUNCTION BEGIN
+# Add error message
+# ARGUMENTS:
+#   $1 (string) Error message.
+# PRINT:
+#   echo message on stderr
+# GLOBALS:
+#   ERRORS
+### FUNCTION END
+error() {
+    local message="$1"
+    
+    ERRORS+="\n${message}"
+    echo "$message" >&2
 }
 
 #=========================================================#
 #                           MAIN                          #
 #=========================================================#
-while getopts "h" option; do
-   case "${option}" in
-      h)
-         usage
-         exit 0
+while getopts "fh" option; do
+    case "${option}" in
+    h)
+        usage
+        exit 0
       ;;
-      *)
-         usage
-         exit 1
+    f)
+        FORCE=true
+      ;;
+    *)
+        usage
+        exit 1
    esac
 done
 
-APP="$1"
-
-if [ -z "$APP" ]; then
-    echo "Error : This script expects a yuno-archive app id as first argument" >&2
-    usage
-    exit 1
+if [[ ! $FORCE && $(yunohost app setting "__APP__" state) == "ongoing" ]]; then
+    error "[ERROR] There is another backup process running. Abord.\nIf the problem persist after reboot, call '$SCRIPT_PATH' with -f option"
+    end_script 1
 fi
 
 now="$(date "+%Y-%m-%d %H:%M:%S")"
-echo "${now} STARTING BACKUP ${APP}" >> "$LOG_FILE"
+echo "${now} STARTING BACKUP __APP__" | tee -a "$LOG_FILE"
 
-# Backup system part conf
-conf=$(sudo yunohost app setting "${APP}" conf)
-if [[ "$conf" = "1" ]]; then
-    echo "--------- BACKUP CONF ---------" >> "$LOG_FILE"
-    if ! sudo yunohost backup create --name "${CURRENT_DATE}_system_conf" --method "${APP}_app" --system "$(filter_hooks conf)" >> "$LOG_FILE" 2>&1; then
-        ERRORS+="\n[ERROR] The backup miserably failed to backup system configurations."
-    fi
+# system hooks methods setted with configuration
+declare -a system=()
+
+# Add system hooks according to configuration
+save_system_conf=$(sudo yunohost app setting "__APP__" save_system_conf)
+if [[ "$save_system_conf" == "1" ]]; then
+    echo "Conf enabled, add to backup script..." | tee -a "$LOG_FILE"
+
+    for hook in $(filter_hooks conf); do
+        system+=("$hook")
+        echo "- Hook '$hook' added" | tee -a "$LOG_FILE"
+    done
 fi
 
-# Backup system data
-data=$(sudo yunohost app setting "${APP}" data)
-if [[ "$data" = "1" ]]; then
-    echo "--------- BACKUP SYSTEM DATA ---------" >> "$LOG_FILE"
-    if ! sudo yunohost backup create --name "${CURRENT_DATE}_system_data" --method "${APP}_app" --system "$(filter_hooks data)" >> "$LOG_FILE" 2>&1; then
-        ERRORS+="\n[ERROR] The backup miserably failed to backup system data."
-    fi
+# Add data hook according to configuration (without data_multimedia hook)
+save_data=$(sudo yunohost app setting "__APP__" save_data)
+if [[ "$save_data" == "1" ]]; then
+    echo "Data enabled, add to backup script..." | tee -a "$LOG_FILE"
+
+    for hook in $(filter_hooks data | grep -v 'data_multimedia'); do
+        system+=("$hook")
+        echo "- Hook '$hook' added" | tee -a "$LOG_FILE"
+    done
 fi
 
-# Backup all apps independently
-apps=$(sudo yunohost app setting "${APP}" apps | tr -d ' ')
+# Add data multimedia according to configuration
+save_data_multimedia=$(sudo yunohost app setting "__APP__" save_data_multimedia)
+if [[ "$save_data_multimedia" == "1" ]]; then
+    echo "Data multimedia enabled, add to backup script..." | tee -a "$LOG_FILE"
+    # Disable .nobackup file if exists
+    if [[ -e  /home/yunohost.multimedia/.nobackup ]]; then
+        mv /home/yunohost.multimedia/.nobackup /home/yunohost.multimedia/.nobackup_disabled
+    fi
+
+    system+=("data_multimedia")
+    echo "- Hook 'data_multimedia' added" | tee -a "$LOG_FILE"
+fi
+
+# Add apps according to configuration
+declare -a apps=()
+save_apps=$(sudo yunohost app setting "__APP__" apps | tr -d ' ')
+echo "Add apps to backup script..." | tee -a "$LOG_FILE"
 for application in $(sudo ls /etc/yunohost/apps/); do
 
-    if ( [[ "$apps" =~ ^exclude: ]] && grep -wq "$application" <<< "$apps" ) ||
-       ( [[ "$apps" != "all" ]] && [[ ! "$apps" =~ ^exclude: ]]  && ! grep -wq "$application" <<< "$apps" );
+    if ( [[ "$save_apps" =~ ^exclude: ]] && grep -wq "$application" <<< "$save_apps" ) ||
+       ( [[ "$save_apps" != "all" ]] && [[ ! "$save_apps" =~ ^exclude: ]]  && ! grep -wq "$application" <<< "$save_apps" );
     then
         continue
     fi
 
     if sudo test ! -f "/etc/yunohost/apps/$application/scripts/backup" ; then
-        ERRORS+="\n[WARN] The application $application has no backup script. This app won't be backed up."
+        error "[WARN] The application $application has no backup script. This app won't be backed up."
         continue
     fi
 
-    echo "--------- BACKUP APP $application ---------" >> "$LOG_FILE"
-    if ! sudo yunohost backup create --name "${CURRENT_DATE}_$application" --method "${APP}_app" --apps "$application" >> "$LOG_FILE" 2>&1; then
-        ERRORS+="\n[ERROR] The backup miserably failed to backup $application application."
-    fi
+    apps+=("$application")
+    echo "Apps '$application' added'" | tee -a "$LOG_FILE"
 done
 
-now="$(date "+%Y-%m-%d %H:%M:%S")"
-echo "${now} END BACKUP ${APP}" >> "$LOG_FILE"
+if [[ ${#apps[@]} -eq 0 && ${#system[@]} -eq 0 ]]; then
+    error "[WARN] apps and system are empty, nothing to save."
+else
+    # Define apps option
+    option_apps=""
+    if [[ ${#apps[@]} -ne 0 ]]; then
+        option_apps=" --apps ${apps[*]}"
+    fi
 
-#=========================================================
-# SEND MAIL TO NOTIFY ABOUT SUCCEEDED OR FAILED OPERATIONS
-#=========================================================
+    # Define system option
+    option_system=""
+    if [[ ${#system[@]} -ne 0 ]]; then
+        option_system=" --system ${system[*]}"
+    fi
 
-method="$(sudo yunohost app setting "${APP}" method)"
-repository="$(sudo yunohost app setting "${APP}" "${method}_repository")"
-mailalert="$(sudo yunohost app setting "${APP}" mailalert)"
-if [[  -n "$ERRORS" && $mailalert != "never" ]]; then
-    cat <(echo -e "$ERRORS\n\n\n") "$LOG_FILE" | mail -a "Content-Type: text/plain; charset=UTF-8" -s "[Yuno-archive] Backup ${APP} failed onto $method $repository" admins
-    rm -rf "$LOG_FILE"
-    exit 1
-elif [ "$mailalert" == "always" ]; then
-    mail -a "Content-Type: text/plain; charset=UTF-8" -s "[Yuno-archive] Backup ${APP} succeeded onto $repository" admins < "$LOG_FILE"
-    rm -rf "$LOG_FILE"
-    exit 0
+    current_date=$(date +"%Y%m%d-%H%M%S")
+    if ! sudo yunohost backup create --name "${current_date}___APP__" --method "__APP__" $option_system $option_apps | tee -a "$LOG_FILE" 2>&1; then
+        error "[ERROR] The backup miserably failed to backup."
+    fi
 fi
+
+now="$(date "+%Y-%m-%d %H:%M:%S")"
+echo "${now} END BACKUP __APP__" | tee -a "$LOG_FILE"
+
+
+end_script
