Upgrade to 0.1.0 : change default temp dir to avoid problem with /tmp dir folder too small.

diff --git a/conf/backup_method b/conf/backup_method
--- a/conf/backup_method
+++ b/conf/backup_method
@@ -19,6 +19,10 @@ declare -r LOCAL_REPO="$4"
 declare -r BACKUP_SIZE="$5"
 declare -r BACKUP_DESCRIPTION="$6"
 
+# Export tmp dir root to use yunohost.backup (/tmp is often too small to create archive file)
+export YARCH_TMPDIR="/home/yunohost.backup/yuno-archive_tmp"
+mkdir -p "$YARCH_TMPDIR"
+
 # Info file name
 declare -r INFO_FILE="${BACKUP_TMP_DIR}/info.json"
 
@@ -58,6 +62,13 @@ do_backup() {
 
     yunohost app setting "__APP__" last_run -v "$(date "+%Y-%m-%d %H:%M:%S")"
     yunohost app setting "__APP__" state -v "ongoing"
+    # Check size in tmp dir
+    local available_space_in_temp
+    available_space_in_temp=$(findmnt --target "$YARCH_TMPDIR" --output AVAIL --bytes --noheadings --first-only)
+    if [[ $BACKUP_SIZE -gt $available_space_in_temp ]]; then
+        echo "ERROR : Not enough space to create temp archive (space neeeded = $(hrb "${BACKUP_SIZE}") available space in temp = $(hrb "${available_space_in_temp}"))" >&2
+        fail
+    fi
 
     case "$METHOD" in
         local)
