Update lack of space in temp dir error message

diff --git a/conf/backup_method b/conf/backup_method
--- a/conf/backup_method
+++ b/conf/backup_method
@@ -66,7 +66,7 @@ do_backup() {
     local available_space_in_temp
     available_space_in_temp=$(findmnt --target "$YARCH_TMPDIR" --output AVAIL --bytes --noheadings --first-only)
     if [[ $BACKUP_SIZE -gt $available_space_in_temp ]]; then
-        echo "ERROR : Not enough space to create temp archive (space neeeded = $(hrb "${BACKUP_SIZE}") available space in temp = $(hrb "${available_space_in_temp}"))" >&2
+        echo "ERROR : Not enough space to create temp archive (space neeeded = $(hrb "${BACKUP_SIZE}") available space in temp ($YARCH_TMPDIR) = $(hrb "${available_space_in_temp}"))" >&2
         fail
     fi
 
