Upgrade to 0.4.0
* Improve backup method to use helpers
* Add incremental  option
* Modify install upgrade and restore to add new files
* Add scp option
* Add scp descriptions
* Upgrade to 0.4.0
* Improve comments and log messages
---------
Co-authored-by: yunohost-bot <yunohost@yunohost.org>

diff --git a/conf/backup_method b/conf/backup_method
--- a/conf/backup_method
+++ b/conf/backup_method
@@ -2,63 +2,96 @@
 # Fail on error
 set -Eeuo pipefail
 
+source "__INSTALL_DIR__/script_helpers"
+
 #=========================================================#
 #                     GLOBAL VARS                         #
 #=========================================================#
 
-# This script
-declare -r THIS_SCRIPT="$(readlink -f "${BASH_SOURCE}")"
-
 # yuno-archive script
-declare -r YUNO_ARCHIVE='__INSTALL_DIR__/yuno-archive.sh'
-
-# log file
-declare -r LOG='/var/log/__APP__/backup.log'
+readonly YUNO_ARCHIVE='__INSTALL_DIR__/yuno-archive.sh'
 
 # Params sent by yunohost backup script
-declare -r BACKUP_TMP_DIR="$2"
-declare -r BACKUP_NAME="$3"
-declare -r LOCAL_REPO="$4"
-declare -r BACKUP_SIZE="$5"
-declare -r BACKUP_DESCRIPTION="$6"
+readonly BACKUP_TMP_DIR="$2"
+readonly BACKUP_NAME="$3"
+#" readonly LOCAL_REPO="$4" unused but keep it just in case
+readonly BACKUP_SIZE="$5"
+# readonly BACKUP_DESCRIPTION="$6" unused but keep it just in case
 
 # Export tmp dir root to use yunohost.backup (/tmp is often too small to create archive file)
 # We use this in order to avoid multiple temp folder in yunohost.backup dir if app crashes before cleanup
 export YARCH_TMPDIR="/home/yunohost.backup/tmp___APP__"
 mkdir -p "$YARCH_TMPDIR"
 # cleanup previous temp files (if app creshed)
-rm -rf "$YARCH_TMPDIR"/*
+rm -rf "${YARCH_TMPDIR:?}"/*
 
 # Info file name
-declare -r INFO_FILE="${BACKUP_TMP_DIR}/info.json"
+readonly INFO_FILE="${BACKUP_TMP_DIR}/info.json"
 
 # Hook script
-declare -r HOOK_FILE="__INSTALL_DIR__/backup_hook"
-
-# App config
-IS_DEFAULT_REPO=$(yunohost app setting "__APP__" ynh_repo)
-
-LOCAL_REPOSITORY="/home/yunohost.backup/archives"
-if [[ $IS_DEFAULT_REPO == "0" ]]; then
-    LOCAL_REPOSITORY=$(yunohost app setting "__APP__" local_repository)
-fi
-DRIVE_REPOSITORY=$(yunohost app setting "__APP__" drive_repository)
-RCLONE_REPOSITORY=$(yunohost app setting "__APP__" rclone_repository)
-
-METHOD=$(yunohost app setting "__APP__" method)
-KEEP=$(yunohost app setting "__APP__" keep)
-
-# Verbose flag 1 = true, 0 = false
-VERBOSE=$(yunohost app setting "__APP__" debug)
+readonly HOOK_FILE="__INSTALL_DIR__/backup_hook"
 
 #=========================================================#
 #                    SCRIPT FUNCTIONS                     #
 #=========================================================#
 
-fail() {
-    yunohost app setting "__APP__" state -v "failed"
-    exit 1
+# Get backup name, this name is deducted from config
+# If we use an incremental backup we get the last incremental backup number and 
+# determine if this number is over the max incremental number
+# If over incremental number or not incremental, we use BACKUP_NAME
+# OUTPUTS:
+# 	Prints backup name to stdout
+create_backup_name() {
+    if [[ $( get_conf is_incremental ) != "1" ]]; then
+        echo "${BACKUP_NAME}"
+        return 0
+    fi
+
+    local max_incremental_number
+    max_incremental_number=$( get_conf max_incremental_number )
+    local last_incremental_number
+    last_incremental_number=$( get_conf last_incremental_number )
+    local origin_incremental_name
+    origin_incremental_name=$( get_conf origin_incremental_name )
+
+    if [[ -z $origin_incremental_name || -z $last_incremental_number || -z $max_incremental_number ]]; then
+        echo "${BACKUP_NAME}"
+        return 0
+    fi
+
+    if [[ $last_incremental_number -ge $max_incremental_number ]]; then
+        echo "${BACKUP_NAME}"
+        return 0
+    fi
+
+    echo "$origin_incremental_name"
 }
+
+# Update increment name to configuration
+# Check conf if incremental and fetch last incremental number to add 1 to value
+update_incremental_name() {
+    local name="$1"
+
+    if [[ $( get_conf is_incremental ) != "1" ]]; then
+        return 0
+    fi
+
+    local last_incremental_number
+    last_incremental_number=$( get_conf last_incremental_number )
+    local new_incremental_number
+    local max_incremental_number
+    max_incremental_number=$( get_conf max_incremental_number )
+
+    if [[ -z $last_incremental_number || $last_incremental_number -ge $max_incremental_number ]]; then
+        new_incremental_number=0
+    else
+        new_incremental_number=$(( last_incremental_number + 1 ))
+    fi
+
+    set_conf origin_incremental_name "$name"
+    set_conf last_incremental_number "$new_incremental_number"
+}
+
 
 do_need_mount() {
     true
@@ -68,12 +101,14 @@ do_mount() {
     true
 }
 
+# Execute backup action according to configuration
+# fail if an error occured
 do_backup() {
+    local method
+    method=$(get_conf_method)
 
-    echo "---------- BEGIN BACKUP ${BACKUP_NAME} ${METHOD} FROM ${THIS_SCRIPT} -----------" | tee -a "$LOG"
-
-    yunohost app setting "__APP__" last_run -v "$(date "+%Y-%m-%d %H:%M:%S")"
-    yunohost app setting "__APP__" state -v "ongoing"
+    set_conf last_run "$(date "+%Y-%m-%d %H:%M:%S")"
+    set_conf state ongoing
     # Check size in tmp dir
     local available_space_in_temp
     available_space_in_temp=$(findmnt --target "$YARCH_TMPDIR" --output AVAIL --bytes --noheadings --first-only)
@@ -83,68 +118,113 @@ do_backup() {
     fi
 
     local verbose_option=""
-    if [[ $VERBOSE == "1" ]]; then
+    if [[ $( get_conf debug ) == "1" ]]; then
         verbose_option="--verbose"
     fi
 
-    case "$METHOD" in
+    local incremental_option=""
+    if [[ $( get_conf is_incremental ) == "1" ]]; then
+        incremental_option="--incremental"
+    fi
+
+    local keep
+    keep=$( get_conf keep )
+
+    local repository
+    repository=$( get_conf_repository )
+
+    local name
+    name=$( create_backup_name )
+
+    case "$method" in
     local)
         $YUNO_ARCHIVE backup local \
-            --log="$LOG" \
-            --repository="$LOCAL_REPOSITORY" \
-            --name="$BACKUP_NAME" \
+            --log="${YUNO_ARCHIVE_LOG_FILE}" \
+            --repository="${repository}" \
+            --name="${name}" \
             --source="$BACKUP_TMP_DIR" \
             --compress="gzip" \
             --info="${INFO_FILE}" \
-            --keep="$KEEP" \
+            --keep="${keep}" \
             --hook="${HOOK_FILE}" \
-            "${verbose_option}" ||
+            "${verbose_option}" \
+            "${incremental_option}" ||
             fail
         ;;
     # We won't fail with send_to_drive method because this method could be called directly in command line
     drive | send_to_drive)
         $YUNO_ARCHIVE backup drive \
-            --log="$LOG" \
-            --drive="$DRIVE_REPOSITORY" \
+            --log="${YUNO_ARCHIVE_LOG_FILE}" \
+            --drive="${repository}" \
             --repository="ynh_archives" \
-            --name="$BACKUP_NAME" \
+            --name="${name}" \
             --source="$BACKUP_TMP_DIR" \
             --compress="gzip" \
             --info="${INFO_FILE}" \
-            --keep="$KEEP" \
+            --keep="${keep}" \
             --hook="${HOOK_FILE}" \
-            "${verbose_option}" ||
+            "${verbose_option}" \
+            "${incremental_option}" ||
             fail
         ;;
     # We won't fail with send_to_drive method because this method could be called directly in command line
     rclone | send_to_rclone)
         $YUNO_ARCHIVE backup rclone \
-            --log="$LOG" \
-            --repository="$RCLONE_REPOSITORY" \
+            --log="${YUNO_ARCHIVE_LOG_FILE}" \
+            --repository="${repository}" \
             --path="ynh_archives" \
-            --name="$BACKUP_NAME" \
+            --name="${name}" \
             --source="$BACKUP_TMP_DIR" \
             --compress="gzip" \
             --info="${INFO_FILE}" \
-            --keep="$KEEP" \
+            --keep="${keep}" \
             --hook="${HOOK_FILE}" \
-            "${verbose_option}" ||
+            "${verbose_option}" \
+            "${incremental_option}" ||
+            fail
+        ;;
+    scp | send_to_scp)
+        $YUNO_ARCHIVE backup scp \
+            --log="${YUNO_ARCHIVE_LOG_FILE}" \
+            --repository="${repository}" \
+            --name="${name}" \
+            --source="$BACKUP_TMP_DIR" \
+            --compress="gzip" \
+            --info="${INFO_FILE}" \
+            --keep="${keep}" \
+            --hook="${HOOK_FILE}" \
+            "${verbose_option}" \
+            "${incremental_option}" ||
             fail
         ;;
     *)
-        echo "Unknown method '$METHOD'" >&2
+        echo "Unknown method '$method'" >&2
         fail
         ;;
     esac
 
-    # To make backup visible on yunohost Backup local menu, we modify name file and add a symbolic link with only tar name
-    if [[ $IS_DEFAULT_REPO == "1" ]]; then
-        mv "${LOCAL_REPOSITORY}/${BACKUP_NAME}.tar.gzip" "${LOCAL_REPOSITORY}/${BACKUP_NAME}.tar.gz"
-        ln -sfn "${LOCAL_REPOSITORY}/${BACKUP_NAME}.tar.gz" "${LOCAL_REPOSITORY}/${BACKUP_NAME}.tar"
+    update_incremental_name "$name"
+
+     # To make backup visible on yunohost Backup local menu, we add a symbolic link with only tar name
+    if [[ $( get_conf ynh_repo ) == "1" ]]; then
+        readonly ynh_archive_dir="/home/yunohost.backup/archives"
+
+        local increment_suffix_name=""
+
+        if [[ $( get_conf is_incremental ) == '1' ]]; then
+            # last_incremental_number as been updated by update_incremental_name
+            if [[ $( get_conf last_incremental_number ) == "0" ]]; then
+                increment_suffix_name='.base'
+            else
+                increment_suffix_name=".inc${new_incremental_number}"
+            fi
+        fi
+
+        local backup_name="${name}${increment_suffix_name}"
+        ln -sfn "${ynh_archive_dir}/${backup_name}.tar.gz" "${ynh_archive_dir}/${backup_name}.tar"
     fi
 
-    yunohost app setting "__APP__" state -v "successful"
-    echo "---------- END BACKUP ${BACKUP_NAME} ${METHOD} FROM ${THIS_SCRIPT} -----------" | tee -a "$LOG"
+    set_conf state successful
     return 0
 }
 
@@ -169,3 +249,4 @@ backup)
 esac
 
 exit 0
+
